### ISSUE TITLE
Linear ring definition flaw

### ISSUE THREAD

**Issue by FelipeMonobe** [geojson/schema#14]
As defined in the "Polygon" section of [RFC 7946](https://tools.ietf.org/html/rfc7946#section-3.1.6), linear rings are **closed** LineStrings, although it has the "four or more positions" rule right, there's a "little" important detail to get them closed: the first and last positions should be the same. Described in the second bullet of the specification. I was also trying to figure out a way to do this, but I'm guessing with today's drafts, it's impossible to guarantee this.

**Comment by tschaub** [comment]
I don't think that JSON Schema will allow us to validate this detail.  In addition to not validating that linear rings are closed, this schema does not validate that linear rings follow the right hand rule.  Since these elements of the spec are not able to be represented in JSON Schema, it is up to the parser to apply this additional validation.
